CREATE DATABASE PasswordManager;
USE PasswordManager;

CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    createdTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE vault (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(255),
    username VARCHAR(100) NOT NULL,
    password TEXT NOT NULL,
    createdTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
